- name: build docker images
  hosts: localhost
  vars_files:
  - vars.yaml

  tasks:
  - name: Checkout repos
    git:
     repo: 'https://github.com/geneontology/{{ item.key }}.git'
     dest: ./{{ item.key }}
     version: '{{ item.value }}'
     force: yes 
    loop: '{{ repo_map|dict2items }}'

  - name: Setting cwd to current directory
    set_fact:
     cwd: "{{ lookup('env', 'PWD') }}"

  - name: build minerva container image
    docker_image:
      name: '{{ docker_hub_user }}/minerva:{{ tag }}'
      source: build
      build:
        dockerfile: '{{ cwd }}/docker/Dockerfile.minerva'
        path: '{{ cwd }}/minerva'
        pull: no
      state: present

  - name: build noctua container image
    docker_image:
      name: '{{ docker_hub_user }}/noctua:{{ tag }}'
      source: build
      build:
        dockerfile: '{{ cwd }}/docker/Dockerfile.noctua'
        path: '{{ cwd }}/noctua'
        pull: no
      state: present

  - name: build golr container image
    docker_image:
      name: '{{ docker_hub_user }}/golr:{{ tag }}'
      source: build
      build:
        dockerfile: '{{ cwd }}/docker/Dockerfile.golr'
        path: '{{ cwd }}/amigo'
        pull: no
      state: present
