- hosts: localhost
  vars_files:
  - vars.yaml

  tasks:
  - name: Tag minerva and push to docker hub
    docker_image:
      name: '{{ docker_hub_user }}/minerva:{{ tag }}'
      repository: '{{ docker_hub_user }}/minerva:{{ tag }}'
      push: yes
      source: local

  - name: Tag noctua and push to docker hub
    docker_image:
      name: '{{ docker_hub_user }}/noctua:{{ tag }}'
      repository: '{{ docker_hub_user }}/noctua:{{ tag }}'
      push: yes
      source: local

  - name: Tag golr and push to docker hub
    docker_image:
      name: '{{ docker_hub_user }}/golr:{{ tag }}'
      repository: '{{ docker_hub_user }}/golr:{{ tag }}'
      push: yes
      source: local
