- hosts: all
  vars_files:
  - vars.yaml
  - docker-vars.yaml

  tasks:
  - name: Create stage directory
    file:
      path: '{{ stage_dir }}/{{ item }}'
      state: directory
    with_items:
      - conf
      - barista
      - httpd-confs
      - srv-solr-data

  - name: install configs from templates directory
    template:
      src: '{{ item.file }}'
      dest: '{{ stage_dir }}/{{ item.dir }}'
    with_items:
      - { file: 'startup.yaml', dir: 'conf' }
      - { file: 'local.yaml', dir: 'barista' }
      - { file: 'docker-compose-amigo.yaml', dir: '' }
      - { file: 'docker-compose-golr.yaml', dir: '' }
      - { file: 'httpd.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-amigo.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-golr.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-barista.conf', dir: 'httpd-confs' }
      - { file: 'httpd-vhosts-noctua.conf', dir: 'httpd-confs' }

  - name: Check if repo is staged
    stat:
      path: '{{ stage_dir }}/{{ item.key }}'
      get_checksum: False
      get_md5: False
    register: staged_repos_results
    loop: '{{ staged_repos|dict2items }}'

  - name: Clone repos that are not staged
    git:
     repo: 'https://github.com/geneontology/{{ item.item.key }}.git'
     dest: '{{ stage_dir }}/{{ item.item.key }}'
     version: '{{ item.item.value }}'
    loop: '{{ staged_repos_results.results }}'
    when: not item.stat.exists

  - name: Check if journal exists 
    stat:
      path: '{{ stage_dir }}/blazegraph.jnl'
      get_checksum: False
      get_md5: False
    register: journal_result 
  - name: Create journal blazegraph.jnl
    shell: | 
         export CMD="java -jar minerva-cli.jar --import-owl-models -j /sdir/blazegraph.jnl -f /sdir/noctua-models/models"
         docker run --rm \
                -v '{{ stage_dir }}:/sdir' \
                -t '{{ docker_hub_user }}/minerva:{{ tag }}' $CMD 
    args:
      executable: /bin/bash
    when: not journal_result.stat.exists

  - name: Check if index exists
    stat:
      path: '{{ stage_dir }}/srv-solr-data/index'
      get_checksum: False
      get_md5: False
    register: index_result
  - name: Create Solr Index
    shell: | 
         docker run --rm \
                -e GOLR_SOLR_MEMORY=4G \
                -e GOLR_LOADER_MEMORY=8G \
                -e GOLR_INPUT_ONTOLOGIES=http://purl.obolibrary.org/obo/ncbitaxon/subsets/taxslim.owl \
                -v '{{ stage_dir }}/srv-solr-data:/srv/solr/data' \
                -t geneontology/golr-autoindex-ontology 
    args:
      executable: /bin/bash
    when: not index_result.stat.exists
